### ISSUE TITLE
Modify Problem interface to make passing full Individuals optional

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#193]
**Task**: adjust `Problem.evaluate()` to take an argument of the form `phenome, *args, **kwargs` instead of `individual`, and work out a custom operator and/or `Individual` subclass to pass in the individual as a `kwarg` when a `Problem` needs it.

**Impact**: this partially rolls back the refactor from #191, which converted all problems over to take an `Individual` instead of a phenome.  The new, heavier payload, however, does not play well with `dask` distribution (which prefers small amounts of data to be passed into workers), so we'd like to pass only phenomes in most cases, leaving open the option of passing extra data when it is needed.

 - [x] Draft modifications
 - Test suite
   - [x] Unit tests pass 
   - [x] Examples pass (except Coevolution)
   - [x] Jupyter notebooks pass
 - [x] Fix Coevolution-via-fitness-functions example

**Comment by SigmaX** [comment]
Picking this back up.  Only got as far as pulling from `develop` and running tests this morning—will continue in coming days.

**Comment by SigmaX** [comment]
Drafted the changes.  Just need to show that the `kwargs` approach can replace the (now broken) Coevolution use case, and fix the harness of Jupyter notebooks.

**Comment by SigmaX** [comment]
Just awaiting PR merge in #215.
